org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

java_version=21

version=1.0.2-zigcity2
group=dev.lucaargolo

mod_id=charta_casino
mod_name=Charta Casino
mod_author=Deokma
license=MPL-2.0
credits=
description=Blackjack and Texas Hold'em addon for Charta.

minecraft_version=1.21.1
minecraft_version_range=[1.21, 1.21.2)

parchment_minecraft=1.21.1
parchment_version=2024.11.17

neo_form_version=1.21.1-20240808.144430

neoforge_version=21.1.212
neoforge_loader_version_range=[4,)

fabric_version=0.116.7+1.21.1
fabric_loader_version=0.17.3

# Charta base mod paths to built jars (relative to addon root)
charta_version=1.2.5
jei_version=19.27.0.340
rei_version=16.0.799