modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
# Mod client uniquement : ne participe pas au handshake serveur (pas de rejet a la connexion).
displayTest="IGNORE_ALL_VERSION"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="CLIENT"
